In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [6]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['squared_error','absolute_error','friedman_mse'],
'max_features': [None,'sqrt','log2'],
'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose
= 3,n_jobs=-1)
grid.fit(indep, dep)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'random'}:

In [8]:
table=pd.DataFrame.from_dict(re)

In [9]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009909,0.001140,0.003681,0.000582,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.741458,0.660361,0.743245,0.701439,0.687754,0.706851,0.031867,3
1,0.007734,0.000805,0.003318,0.000368,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.717673,0.574621,0.765133,0.713368,0.704295,0.695018,0.063793,9
2,0.007719,0.001801,0.003450,0.000624,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.760617,0.437452,0.758996,0.709950,0.690587,0.671520,0.120182,10
3,0.005598,0.000415,0.003225,0.000924,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.655669,0.653824,0.655640,0.680987,0.688408,0.666906,0.014731,11
4,0.006771,0.000981,0.003147,0.000814,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.667910,0.551199,0.623890,0.692452,0.660339,0.639158,0.049164,17
5,0.006593,0.000773,0.003526,0.000634,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.618092,0.631322,0.697122,0.702763,0.627355,0.655331,0.036721,12
6,0.039248,0.004076,0.003449,0.000696,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.677190,0.672824,0.740775,0.717338,0.728830,0.707392,0.027496,2
7,0.030472,0.002786,0.003829,0.001172,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.737299,0.596911,0.753071,0.695339,0.701840,0.696892,0.054428,8
8,0.022167,0.003366,0.003496,0.000605,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.682081,0.652650,0.783320,0.746594,0.665453,0.706020,0.050376,4
9,0.021754,0.002957,0.003631,0.000660,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.728360,0.680594,0.628293,0.584220,0.607836,0.645861,0.052090,15
10,0.022876,0.001974,0.002945,0.000279,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.705766,0.554273,0.626731,0.685505,0.677319,0.649919,0.054446,14
11,0.020673,0.003076,0.003125,0.000289,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.720141,0.622374,0.485419,0.655356,0.722567,0.641172,0.086804,16
12,0.007633,0.000863,0.003998,0.000623,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.754341,0.647120,0.717032,0.704745,0.679741,0.700596,0.035974,6
13,0.006483,0.000622,0.002765,0.000131,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.727975,0.600895,0.785205,0.762215,0.734682,0.722194,0.063992,1
14,0.004963,0.000356,0.002821,0.000230,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.718846,0.672368,0.731857,0.713377,0.659704,0.699230,0.028048,7
15,0.005181,0.000700,0.002856,0.000082,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.710236,0.572269,0.666372,0.621428,0.684336,0.650928,0.048846,13
16,0.005281,0.000397,0.002400,0.000180,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.778777,0.703982,0.625741,0.701241,0.709760,0.703900,0.048491,5
17,0.004480,0.000364,0.002189,0.000111,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.656245,0.606270,0.556652,0.613069,0.621627,0.610773,0.032063,18

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))