In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
dataset = dataset.drop("User ID",axis=1)

In [6]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent=dataset['Purchased']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid = [
             {
                  'criterion': ['gini','entropy'],
                  'max_features': ['auto','sqrt','log2'],
                  'n_estimators':[10,100]
            
             }
]
grid = GridSearchCV(RandomForestClassifier(),param_grid)
grid.fit(x_train,y_train)

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.88571429 0.89285714 0.86071429 0.875
        nan        nan 0.86428571 0.88928571 0.86428571 0.88571429]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid=[{'criterion': ['gini', 'entropy'],
                          'max_features': ['auto', 'sqrt', 'log2'],
                          'n_estimators': [10, 100]}])

In [13]:
re = grid.cv_results_

In [14]:
print(re)

{'mean_fit_time': array([0.00053697, 0.00052085, 0.01798077, 0.12662458, 0.01267552,
       0.12453856, 0.00040979, 0.00046468, 0.01663103, 0.12913766,
       0.01470041, 0.12930551]), 'std_fit_time': array([8.75363676e-05, 1.81252609e-04, 5.36875947e-03, 6.68575250e-03,
       3.16396133e-04, 8.93159902e-03, 2.87301412e-05, 1.45746898e-04,
       3.06095046e-03, 7.94305739e-03, 6.28007065e-04, 5.47074560e-03]), 'mean_score_time': array([0.        , 0.        , 0.00196304, 0.00660958, 0.00138869,
       0.00573378, 0.        , 0.        , 0.00165401, 0.00591831,
       0.00139184, 0.00652733]), 'std_score_time': array([0.00000000e+00, 0.00000000e+00, 6.35446597e-04, 8.31264319e-04,
       7.19682347e-05, 7.96616949e-05, 0.00000000e+00, 0.00000000e+00,
       2.11511956e-04, 2.33647599e-04, 2.08407843e-05, 8.18642313e-04]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                   'auto', 'sqrt', 'sqrt', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_n_estimators': masked_array(data=[10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'params': [{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}, {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}], 'split0_test_score': array([       nan,        nan, 0.89285714, 0.875     , 0.875     ,
       0.875     ,        nan,        nan, 0.85714286, 0.875     ,
       0.875     , 0.875     ]), 'split1_test_score': array([       nan,        nan, 0.89285714, 0.875     , 0.82142857,
       0.85714286,        nan,        nan, 0.82142857, 0.85714286,
       0.82142857, 0.85714286]), 'split2_test_score': array([       nan,        nan, 0.82142857, 0.85714286, 0.82142857,
       0.82142857,        nan,        nan, 0.85714286, 0.85714286,
       0.80357143, 0.82142857]), 'split3_test_score': array([       nan,        nan, 0.92857143, 0.91071429, 0.91071429,
       0.91071429,        nan,        nan, 0.89285714, 0.91071429,
       0.91071429, 0.91071429]), 'split4_test_score': array([       nan,        nan, 0.89285714, 0.94642857, 0.875     ,
       0.91071429,        nan,        nan, 0.89285714, 0.94642857,
       0.91071429, 0.96428571]), 'mean_test_score': array([       nan,        nan, 0.88571429, 0.89285714, 0.86071429,
       0.875     ,        nan,        nan, 0.86428571, 0.88928571,
       0.86428571, 0.88571429]), 'std_test_score': array([       nan,        nan, 0.03499271, 0.03194383, 0.03462628,
       0.03388155,        nan,        nan, 0.02672612, 0.03462628,
       0.04460713, 0.04870779]), 'rank_test_score': array([9, 9, 3, 1, 8, 5, 9, 9, 6, 2, 6, 3], dtype=int32)}

In [15]:
grid_predictions =grid.predict(x_test)

In [16]:
y_pred=grid.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[74  5]
 [ 5 36]]

In [18]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        79
           1       0.88      0.88      0.88        41

    accuracy                           0.92       120
   macro avg       0.91      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9536894103118246

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000537,0.000088,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000521,0.000181,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.017981,0.005369,0.001963,0.000635,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.892857,0.892857,0.821429,0.928571,0.892857,0.885714,0.034993,3
3,0.126625,0.006686,0.006610,0.000831,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.875000,0.875000,0.857143,0.910714,0.946429,0.892857,0.031944,1
4,0.012676,0.000316,0.001389,0.000072,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.875000,0.821429,0.821429,0.910714,0.875000,0.860714,0.034626,8
5,0.124539,0.008932,0.005734,0.000080,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.875000,0.857143,0.821429,0.910714,0.910714,0.875000,0.033882,5
6,0.000410,0.000029,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000465,0.000146,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.016631,0.003061,0.001654,0.000212,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.857143,0.821429,0.857143,0.892857,0.892857,0.864286,0.026726,6
9,0.129138,0.007943,0.005918,0.000234,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.875000,0.857143,0.857143,0.910714,0.946429,0.889286,0.034626,2
10,0.014700,0.000628,0.001392,0.000021,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.875000,0.821429,0.803571,0.910714,0.910714,0.864286,0.044607,6
11,0.129306,0.005471,0.006527,0.000819,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.875000,0.857143,0.821429,0.910714,0.964286,0.885714,0.048708,3