In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [12]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error','absolute_error'],
'max_features': [None,'sqrt','log2'],
'n_estimators':[10,100]}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose
= 3,n_jobs=-1)
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [16]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.102770,0.026136,0.005371,0.000999,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.824784,0.752336,0.856464,0.783763,0.807405,0.804950,0.035413,12
1,0.491794,0.058929,0.025595,0.001999,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.843706,0.764470,0.851792,0.806006,0.830652,0.819325,0.031507,6
2,0.055818,0.018476,0.004997,0.000388,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.850762,0.751153,0.830342,0.807576,0.821952,0.812357,0.033643,11
3,0.352356,0.030657,0.024888,0.001740,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.854445,0.772606,0.854778,0.824063,0.836549,0.828488,0.030240,4
4,0.048996,0.004071,0.004947,0.000161,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.842621,0.773555,0.846826,0.790344,0.813772,0.813424,0.028602,10
5,0.359392,0.017023,0.023796,0.001550,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856351,0.774560,0.853739,0.822938,0.840000,0.829517,0.029934,3
6,0.216676,0.015461,0.005442,0.000879,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.823929,0.763217,0.838944,0.815842,0.829387,0.814264,0.026606,9
7,1.810378,0.030411,0.013706,0.001006,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.833544,0.756168,0.855893,0.823351,0.831706,0.820132,0.033747,5
8,0.131668,0.008222,0.005515,0.000818,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.841707,0.755048,0.843301,0.818360,0.823376,0.816358,0.032189,7
9,1.122581,0.012967,0.020642,0.001018,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854082,0.778902,0.852868,0.826562,0.837371,0.829957,0.027496,1
10,0.128717,0.012304,0.004926,0.000258,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.844218,0.744615,0.848444,0.821646,0.822607,0.816306,0.037469,8
11,1.129312,0.084094,0.014214,0.001177,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.862836,0.774930,0.849414,0.822038,0.840029,0.829850,0.030501,2

In [19]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 34
BMI: 30
Children: 0
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[4340.28]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(