In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
dataset = dataset.drop("User ID",axis=1)

In [6]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [17]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent=dataset['Purchased']

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid = [
             {
                  'kernel': ['linear','rbf','poly','sigmoid'],
                  'gamma': ['auto','scale'],
                  'C':[10,100,1000]
            
             }
]
grid = GridSearchCV(SVC(probability=True),param_grid)
grid.fit(x_train,y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [10, 100, 1000], 'gamma': ['auto', 'scale'],
                          'kernel': ['linear', 'rbf', 'poly', 'sigmoid']}])

In [21]:
re = grid.cv_results_

In [22]:
print(re)

{'mean_fit_time': array([0.01210818, 0.00666203, 0.00852089, 0.00458779, 0.00681992,
       0.00539026, 0.00746026, 0.00448985, 0.0215476 , 0.00937786,
       0.02572241, 0.00430932, 0.02232175, 0.00833697, 0.02549372,
       0.00454459, 0.18727136, 0.02643099, 0.22194495, 0.00561819,
       0.16700311, 0.0244276 , 0.40412669, 0.00448709]), 'std_fit_time': array([2.84627458e-03, 1.47290886e-03, 2.08869195e-03, 6.24836113e-04,
       3.33038972e-04, 5.81626990e-04, 8.91839101e-04, 3.65795500e-04,
       2.89123627e-03, 2.31425727e-03, 4.51886219e-03, 1.95026666e-04,
       1.14662666e-03, 7.34615416e-04, 5.87133040e-03, 4.20923517e-04,
       5.59019423e-02, 6.83243857e-03, 6.89148403e-02, 2.13745200e-03,
       4.28617804e-02, 4.33616804e-03, 2.34834675e-01, 2.35536822e-04]), 'mean_score_time': array([0.00210476, 0.00144148, 0.00116677, 0.00091667, 0.00090413,
       0.00106111, 0.0009727 , 0.00088997, 0.00094829, 0.00122972,
       0.00097542, 0.00088086, 0.00091276, 0.00099454, 0.00091   ,
       0.0008894 , 0.00132751, 0.00121598, 0.0015882 , 0.00129137,
       0.00137658, 0.00099559, 0.00145717, 0.0009037 ]), 'std_score_time': array([3.61122572e-04, 3.00705739e-04, 4.30499652e-04, 1.67745050e-05,
       4.69657733e-05, 7.39759641e-05, 1.56701735e-04, 1.50119667e-05,
       4.02249946e-05, 3.42436527e-04, 1.42074381e-04, 1.59605881e-05,
       1.56258598e-05, 2.15726527e-05, 3.62372398e-05, 1.06768940e-05,
       5.99037657e-04, 4.32752338e-04, 5.26808100e-04, 4.33075115e-04,
       9.45968971e-05, 1.54199140e-05, 3.17933134e-04, 3.14942189e-05]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 100, 100, 100, 100,
                   100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000,
                   1000, 1000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                   'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'scale', 'auto', 'auto',
                   'auto', 'auto', 'scale', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}], 'split0_test_score': array([0.83928571, 0.89285714, 0.83928571, 0.76785714, 0.83928571,
       0.89285714, 0.83928571, 0.76785714, 0.83928571, 0.85714286,
       0.83928571, 0.76785714, 0.83928571, 0.85714286, 0.83928571,
       0.76785714, 0.83928571, 0.83928571, 0.83928571, 0.76785714,
       0.83928571, 0.83928571, 0.83928571, 0.76785714]), 'split1_test_score': array([0.78571429, 0.875     , 0.80357143, 0.73214286, 0.78571429,
       0.875     , 0.80357143, 0.73214286, 0.78571429, 0.89285714,
       0.80357143, 0.71428571, 0.78571429, 0.89285714, 0.80357143,
       0.71428571, 0.78571429, 0.875     , 0.80357143, 0.71428571,
       0.78571429, 0.875     , 0.80357143, 0.71428571]), 'split2_test_score': array([0.67857143, 0.83928571, 0.75      , 0.73214286, 0.67857143,
       0.83928571, 0.75      , 0.625     , 0.67857143, 0.85714286,
       0.73214286, 0.75      , 0.67857143, 0.85714286, 0.75      ,
       0.75      , 0.67857143, 0.85714286, 0.73214286, 0.75      ,
       0.67857143, 0.85714286, 0.73214286, 0.75      ]), 'split3_test_score': array([0.92857143, 0.94642857, 0.92857143, 0.75      , 0.92857143,
       0.94642857, 0.92857143, 0.75      , 0.92857143, 0.92857143,
       0.92857143, 0.69642857, 0.92857143, 0.92857143, 0.92857143,
       0.75      , 0.92857143, 0.91071429, 0.92857143, 0.69642857,
       0.92857143, 0.91071429, 0.92857143, 0.69642857]), 'split4_test_score': array([0.89285714, 0.94642857, 0.89285714, 0.76785714, 0.89285714,
       0.94642857, 0.89285714, 0.76785714, 0.89285714, 0.92857143,
       0.91071429, 0.76785714, 0.89285714, 0.92857143, 0.91071429,
       0.76785714, 0.89285714, 0.89285714, 0.91071429, 0.76785714,
       0.89285714, 0.89285714, 0.91071429, 0.76785714]), 'mean_test_score': array([0.825     , 0.9       , 0.84285714, 0.75      , 0.825     ,
       0.9       , 0.84285714, 0.72857143, 0.825     , 0.89285714,
       0.84285714, 0.73928571, 0.825     , 0.89285714, 0.84642857,
       0.75      , 0.825     , 0.875     , 0.84285714, 0.73928571,
       0.825     , 0.875     , 0.84285714, 0.73928571]), 'std_test_score': array([0.0877729 , 0.04164966, 0.06328588, 0.01597191, 0.0877729 ,
       0.04164966, 0.06328588, 0.05345225, 0.0877729 , 0.03194383,
       0.07178483, 0.02901442, 0.0877729 , 0.03194383, 0.06643241,
       0.01956152, 0.0877729 , 0.02525381, 0.07178483, 0.02901442,
       0.0877729 , 0.02525381, 0.07178483, 0.02901442]), 'rank_test_score': array([13,  1,  8, 19, 13,  1,  8, 24, 13,  3,  8, 21, 13,  3,  7, 19, 13,
        5,  8, 21, 13,  5,  8, 21], dtype=int32)}

In [23]:
grid_predictions =grid.predict(x_test)

In [24]:
y_pred=grid.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[73  6]
 [ 4 37]]

In [26]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120

In [27]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9654214263661625

In [30]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012108,0.002846,0.002105,0.000361,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
1,0.006662,0.001473,0.001441,0.000301,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.892857,0.875000,0.839286,0.946429,0.946429,0.900000,0.041650,1
2,0.008521,0.002089,0.001167,0.000430,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.839286,0.803571,0.750000,0.928571,0.892857,0.842857,0.063286,8
3,0.004588,0.000625,0.000917,0.000017,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.767857,0.732143,0.732143,0.750000,0.767857,0.750000,0.015972,19
4,0.006820,0.000333,0.000904,0.000047,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
5,0.005390,0.000582,0.001061,0.000074,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.892857,0.875000,0.839286,0.946429,0.946429,0.900000,0.041650,1
6,0.007460,0.000892,0.000973,0.000157,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.839286,0.803571,0.750000,0.928571,0.892857,0.842857,0.063286,8
7,0.004490,0.000366,0.000890,0.000015,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.767857,0.732143,0.625000,0.750000,0.767857,0.728571,0.053452,24
8,0.021548,0.002891,0.000948,0.000040,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
9,0.009378,0.002314,0.001230,0.000342,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.857143,0.892857,0.857143,0.928571,0.928571,0.892857,0.031944,3
10,0.025722,0.004519,0.000975,0.000142,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.839286,0.803571,0.732143,0.928571,0.910714,0.842857,0.071785,8
11,0.004309,0.000195,0.000881,0.000016,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.767857,0.714286,0.750000,0.696429,0.767857,0.739286,0.029014,21
12,0.022322,0.001147,0.000913,0.000016,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
13,0.008337,0.000735,0.000995,0.000022,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.857143,0.892857,0.857143,0.928571,0.928571,0.892857,0.031944,3
14,0.025494,0.005871,0.000910,0.000036,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.839286,0.803571,0.750000,0.928571,0.910714,0.846429,0.066432,7
15,0.004545,0.000421,0.000889,0.000011,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.767857,0.714286,0.750000,0.750000,0.767857,0.750000,0.019562,19
16,0.187271,0.055902,0.001328,0.000599,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
17,0.026431,0.006832,0.001216,0.000433,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.839286,0.875000,0.857143,0.910714,0.892857,0.875000,0.025254,5
18,0.221945,0.068915,0.001588,0.000527,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.839286,0.803571,0.732143,0.928571,0.910714,0.842857,0.071785,8
19,0.005618,0.002137,0.001291,0.000433,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.767857,0.714286,0.750000,0.696429,0.767857,0.739286,0.029014,21
20,0.167003,0.042862,0.001377,0.000095,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.839286,0.785714,0.678571,0.928571,0.892857,0.825000,0.087773,13
21,0.024428,0.004336,0.000996,0.000015,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.839286,0.875000,0.857143,0.910714,0.892857,0.875000,0.025254,5
22,0.404127,0.234835,0.001457,0.000318,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.839286,0.803571,0.732143,0.928571,0.910714,0.842857,0.071785,8
23,0.004487,0.000236,0.000904,0.000031,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.767857,0.714286,0.750000,0.696429,0.767857,0.739286,0.029014,21